"""add plan_artifact_feedback table

Revision ID: 1af17b9d62b6
Revises: 58109bb8d2a2
Create Date: 2025-12-18 19:13:20.676004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af17b9d62b6'
down_revision = '58109bb8d2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_artifact_feedback',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('story_id', sa.String(length=40), nullable=True),
    sa.Column('feedback_human', sa.Text(), nullable=True),
    sa.Column('feedback_ai', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_plan_artifact_feedback_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_artifact_feedback'))
    )
    with op.batch_alter_table('plan_artifact_feedback', schema=None) as batch_op:
        batch_op.create_index('ux_plan_feedback_run_kind_story', ['run_id', 'kind', 'story_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_artifact_feedback', schema=None) as batch_op:
        batch_op.drop_index('ux_plan_feedback_run_kind_story')

    op.drop_table('plan_artifact_feedback')
    # ### end Alembic commands ###
