"""m1.2a planning schema

Revision ID: 1c06a7d8136e
Revises: 89907b0fe163
Create Date: 2025-10-14 15:00:09.072728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c06a7d8136e'
down_revision = '89907b0fe163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.create_index('ix_epics_run_rank', ['run_id', 'priority_rank'], unique=False)

    op.create_table('product_visions',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('technical_solutions',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epic_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('priority_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tests', sa.JSON(), nullable=False))
        batch_op.create_foreign_key('fk_stories_epic', 'epics', ['epic_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tests')
        batch_op.drop_column('priority_rank')
        batch_op.drop_column('epic_id')

    op.drop_table('technical_solutions')
    op.drop_table('product_visions')
    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.drop_index('ix_epics_run_rank')

    op.drop_table('epics')
    # ### end Alembic commands ###
