"""add title to runs

Revision ID: 37ff9cc42d16
Revises: 1c06a7d8136e
Create Date: 2025-10-16 16:00:22.654176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ff9cc42d16'
down_revision = '1c06a7d8136e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
