"""tasks: add order/status + story order index

Revision ID: 58109bb8d2a2
Revises: 3bc11a1b494e
Create Date: 2025-11-25 10:45:25.254650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58109bb8d2a2'
down_revision = '3bc11a1b494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # Add with server_default so SQLite can backfill existing rows
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, server_default=sa.text("1")))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False, server_default=sa.text("'todo'")))
        batch_op.create_index('ix_tasks_story_order', ['run_id', 'story_id', 'order'], unique=False)

    # OPTIONAL: drop the defaults so future inserts must provide values or rely on ORM defaults
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('order', server_default=None)
        batch_op.alter_column('status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_story_order')
        batch_op.drop_column('status')
        batch_op.drop_column('order')

    # ### end Alembic commands ###
