"""Add human/ai feedback to artifacts

Revision ID: 9a6c27df1080
Revises: 37ff9cc42d16
Create Date: 2025-11-21 12:53:16.326036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6c27df1080'
down_revision = '37ff9cc42d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_human', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_ai', sa.Text(), nullable=True))

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_human', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_ai', sa.Text(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_human', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_ai', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('feedback_ai')
        batch_op.drop_column('feedback_human')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('feedback_ai')
        batch_op.drop_column('feedback_human')

    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.drop_column('feedback_ai')
        batch_op.drop_column('feedback_human')

    # ### end Alembic commands ###
